"""Document generation tools for the Worker Agent — professional formatting."""
import os
import uuid
from datetime import datetime

from core.tools import register_tool

GENERATED_FILES_DIR = os.path.join(
    os.path.dirname(os.path.dirname(__file__)), "generated_files"
)
os.makedirs(GENERATED_FILES_DIR, exist_ok=True)

# ─── Colors ───
HEX_TO_RGB = lambda h: tuple(int(h[i : i + 2], 16) for i in (0, 2, 4))

PRIMARY_COLOR = "1a1a2e"  # Dark navy
ACCENT_COLOR = "00ff88"  # Neon green
TEXT_COLOR = "333333"
LIGHT_GRAY = "f5f5f5"


def _snake_to_title(text: str) -> str:
    return " ".join(w.capitalize() for w in text.replace("_", " ").split())


# ═══════════════════════════════════════════════════════════════════════════════
# WORD DOCUMENT (.docx)
# ═══════════════════════════════════════════════════════════════════════════════

@register_tool(
    name="generate_docx",
    description="Generate a Word document (.docx) with text, tables, and embedded chart images. Returns {filename, filepath, format, title, template, file_size}.",
    parameters={
        "properties": {
            "title": {"type": "string", "description": "document title"},
            "template": {"type": "string", "description": "one of: travel_guide, project_plan, modern_report, research_report"},
            "sections": {"type": "array", "description": "list of objects with keys: heading (string), content (string), table (optional: {headers: [string], rows: [[values]]}), chart_image (optional: filepath from generate_chart)"},
        }
    },
)
async def generate_docx(title: str, template: str, sections: list[dict]) -> dict:
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
    from docx.enum.section import WD_ORIENT

    doc = Document()

    # ── Styles ──
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)
    font.color.rgb = RGBColor(*HEX_TO_RGB(TEXT_COLOR))

    # Heading 1 style
    h1 = doc.styles["Heading 1"]
    h1.font.name = "Calibri Light"
    h1.font.size = Pt(20)
    h1.font.bold = True
    h1.font.color.rgb = RGBColor(*HEX_TO_RGB(PRIMARY_COLOR))

    # Heading 2 style
    h2 = doc.styles["Heading 2"]
    h2.font.name = "Calibri Light"
    h2.font.size = Pt(16)
    h2.font.bold = True
    h2.font.color.rgb = RGBColor(*HEX_TO_RGB(ACCENT_COLOR))

    # ── Cover Page ──
    doc.add_paragraph()  # spacing
    doc.add_paragraph()
    title_para = doc.add_paragraph()
    title_run = title_para.add_run(title)
    title_run.font.size = Pt(32)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(*HEX_TO_RGB(PRIMARY_COLOR))
    title_run.font.name = "Calibri Light"
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = doc.add_paragraph()
    sub_run = subtitle.add_run(_snake_to_title(template))
    sub_run.font.size = Pt(16)
    sub_run.font.color.rgb = RGBColor(*HEX_TO_RGB(ACCENT_COLOR))
    sub_run.font.name = "Calibri Light"
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()
    date_para = doc.add_paragraph()
    date_run = date_para.add_run(
        f"Generated by Life OS — {datetime.now().strftime('%B %d, %Y')}"
    )
    date_run.font.size = Pt(10)
    date_run.font.color.rgb = RGBColor(128, 128, 128)
    date_run.font.italic = True
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_page_break()

    # ── Sections ──
    for section in sections:
        heading = section.get("heading", "")
        content = section.get("content", "")

        doc.add_heading(heading, level=1)

        # Content paragraphs
        for para_text in content.split("\n"):
            para_text = para_text.strip()
            if not para_text:
                continue
            if para_text.startswith("- ") or para_text.startswith("• "):
                p = doc.add_paragraph(para_text[2:].strip(), style="List Bullet")
            elif para_text.startswith("1. ") or para_text.startswith("2. "):
                p = doc.add_paragraph(para_text[3:].strip(), style="List Number")
            else:
                p = doc.add_paragraph(para_text)

        # Optional table
        table_data = section.get("table")
        if table_data:
            headers = table_data.get("headers", [])
            rows = table_data.get("rows", [])
            if headers and rows:
                table = doc.add_table(rows=1 + len(rows), cols=len(headers))
                table.style = "Table Grid"
                table.alignment = WD_TABLE_ALIGNMENT.CENTER

                # Header row
                for i, h in enumerate(headers):
                    cell = table.rows[0].cells[i]
                    cell.text = str(h)
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.font.bold = True
                            run.font.color.rgb = RGBColor(255, 255, 255)
                    cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
                    # Dark background
                    shading = cell._element.get_or_add_tcPr()
                    from docx.oxml.ns import qn

                    shading.append(
                        parse_xml(
                            r'<w:shd {} w:fill="{}"/>'.format(
                                nsdecls("w"), PRIMARY_COLOR
                            )
                        )
                    )

                # Data rows
                for r_idx, row in enumerate(rows):
                    for c_idx, val in enumerate(row):
                        cell = table.rows[r_idx + 1].cells[c_idx]
                        cell.text = str(val)
                        cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
                        # Alternate row colors
                        if r_idx % 2 == 1:
                            shading = cell._element.get_or_add_tcPr()
                            shading.append(
                                parse_xml(
                                    r'<w:shd {} w:fill="{}"/>'.format(
                                        nsdecls("w"), LIGHT_GRAY
                                    )
                                )
                            )

        # Optional chart image
        chart_image = section.get("chart_image")
        if chart_image and os.path.exists(chart_image):
            doc.add_paragraph()
            doc.add_picture(chart_image, width=Inches(5.5))
            last_paragraph = doc.paragraphs[-1]
            last_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_paragraph()  # spacing between sections

    # ── Footer ──
    for section in doc.sections:
        footer = section.footer
        footer_para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        footer_para.text = f"Life OS — {title} — Page "
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    filename = f"{uuid.uuid4().hex[:8]}_{title.replace(' ', '_')[:30]}.docx"
    filepath = os.path.join(GENERATED_FILES_DIR, filename)
    doc.save(filepath)

    return {
        "filename": filename,
        "filepath": filepath,
        "format": "docx",
        "title": title,
        "template": template,
        "file_size": os.path.getsize(filepath),
    }


# Need these imports for the docx shading hack
from docx.oxml import parse_xml
from docx.oxml.ns import nsdecls


# ═══════════════════════════════════════════════════════════════════════════════
# EXCEL SPREADSHEET (.xlsx)
# ═══════════════════════════════════════════════════════════════════════════════

@register_tool(
    name="generate_xlsx",
    description="Generate an Excel spreadsheet (.xlsx) with styled sheets, charts, and optional summary rows. Returns {filename, filepath, format, title, template, file_size}.",
    parameters={
        "properties": {
            "title": {"type": "string", "description": "spreadsheet title"},
            "template": {"type": "string", "description": "one of: budget_tracker, comparison_sheet"},
            "sheets": {"type": "array", "description": "list of objects with keys: name (string), headers ([string]), rows ([[values]]), chart_type (optional: 'bar'|'pie'|'line'), summary (optional: 'totals'|'averages'|'both' — adds a summary row at the bottom for numeric columns)"},
        }
    },
)
async def generate_xlsx(
    title: str, template: str, sheets: list[dict]
) -> dict:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter
    from openpyxl.chart import BarChart, PieChart, LineChart, Reference

    wb = Workbook()
    wb.remove(wb.active)  # Remove default sheet

    # ── Styles ──
    header_font = Font(name="Calibri", size=12, bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color=PRIMARY_COLOR, end_color=PRIMARY_COLOR, fill_type="solid")
    header_align = Alignment(horizontal="center", vertical="center")

    data_font = Font(name="Calibri", size=11)
    data_align = Alignment(horizontal="left", vertical="center")
    number_align = Alignment(horizontal="right", vertical="center")

    alt_fill = PatternFill(start_color=LIGHT_GRAY, end_color=LIGHT_GRAY, fill_type="solid")
    accent_fill = PatternFill(start_color="E8F5E9", end_color="E8F5E9", fill_type="solid")

    thin_border = Border(
        left=Side(style="thin", color="DDDDDD"),
        right=Side(style="thin", color="DDDDDD"),
        top=Side(style="thin", color="DDDDDD"),
        bottom=Side(style="thin", color="DDDDDD"),
    )

    for sheet_def in sheets:
        sheet_name = sheet_def.get("name", "Sheet")[:31]
        ws = wb.create_sheet(title=sheet_name)

        headers = sheet_def.get("headers", [])
        rows = sheet_def.get("rows", [])
        chart_type = sheet_def.get("chart_type")

        # ── Title row ──
        ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=max(len(headers), 1))
        title_cell = ws.cell(row=1, column=1, value=title)
        title_cell.font = Font(name="Calibri Light", size=18, bold=True, color=PRIMARY_COLOR)
        title_cell.alignment = Alignment(horizontal="center", vertical="center")
        ws.row_dimensions[1].height = 30

        # ── Headers ──
        if headers:
            for col_idx, header in enumerate(headers, 1):
                cell = ws.cell(row=3, column=col_idx, value=header)
                cell.font = header_font
                cell.fill = header_fill
                cell.alignment = header_align
                cell.border = thin_border
            ws.row_dimensions[3].height = 22

        # ── Data rows ──
        for row_idx, row in enumerate(rows, 4):
            for col_idx, val in enumerate(row, 1):
                cell = ws.cell(row=row_idx, column=col_idx, value=val)
                cell.font = data_font
                cell.border = thin_border

                # Alternate row coloring
                if (row_idx - 4) % 2 == 1:
                    cell.fill = alt_fill

                # Number alignment for numeric values
                if isinstance(val, (int, float)):
                    cell.alignment = number_align
                    # Currency format for budget sheets
                    if template == "budget_tracker" and col_idx > 1:
                        cell.number_format = '$#,##0.00'
                else:
                    cell.alignment = data_align

        # ── Auto column width ──
        for col_idx in range(1, len(headers) + 1):
            max_len = 0
            for row in ws.iter_rows(min_row=3, max_row=ws.max_row, min_col=col_idx, max_col=col_idx):
                for cell in row:
                    if cell.value:
                        max_len = max(max_len, len(str(cell.value)))
            ws.column_dimensions[get_column_letter(col_idx)].width = min(max_len + 4, 50)

        # ── Summary rows ──
        summary = sheet_def.get("summary")
        if summary and rows and headers:
            summary_row_start = len(rows) + 4
            summary_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
            summary_fill = PatternFill(start_color="2d2d44", end_color="2d2d44", fill_type="solid")

            if summary in ("totals", "both"):
                ws.cell(row=summary_row_start, column=1, value="TOTAL").font = summary_font
                ws.cell(row=summary_row_start, column=1).fill = summary_fill
                ws.cell(row=summary_row_start, column=1).border = thin_border
                for col_idx in range(2, len(headers) + 1):
                    col_letter = get_column_letter(col_idx)
                    formula = f"=SUM({col_letter}4:{col_letter}{summary_row_start - 1})"
                    cell = ws.cell(row=summary_row_start, column=col_idx, value=formula)
                    cell.font = summary_font
                    cell.fill = summary_fill
                    cell.border = thin_border
                    cell.alignment = number_align
                    if template == "budget_tracker":
                        cell.number_format = '$#,##0.00'
                summary_row_start += 1

            if summary in ("averages", "both"):
                ws.cell(row=summary_row_start, column=1, value="AVERAGE").font = summary_font
                ws.cell(row=summary_row_start, column=1).fill = summary_fill
                ws.cell(row=summary_row_start, column=1).border = thin_border
                for col_idx in range(2, len(headers) + 1):
                    col_letter = get_column_letter(col_idx)
                    formula = f"=AVERAGE({col_letter}4:{col_letter}{summary_row_start - 1})"
                    cell = ws.cell(row=summary_row_start, column=col_idx, value=formula)
                    cell.font = summary_font
                    cell.fill = summary_fill
                    cell.border = thin_border
                    cell.alignment = number_align

        # ── Freeze panes ──
        if headers:
            ws.freeze_panes = "A4"

        # ── Chart ──
        if chart_type and len(rows) > 0 and len(headers) >= 2:
            chart_classes = {"bar": BarChart, "pie": PieChart, "line": LineChart}
            ChartClass = chart_classes.get(chart_type, BarChart)
            chart = ChartClass()
            chart.title = sheet_name
            chart.style = 10

            data = Reference(
                ws,
                min_col=2,
                min_row=3,
                max_col=len(headers),
                max_row=len(rows) + 3,
            )
            cats = Reference(ws, min_col=1, min_row=4, max_row=len(rows) + 3)
            chart.add_data(data, titles_from_data=True)
            chart.set_categories(cats)
            chart.width = 18
            chart.height = 10
            ws.add_chart(chart, f"A{len(rows) + 6}")

    filename = f"{uuid.uuid4().hex[:8]}_{title.replace(' ', '_')[:30]}.xlsx"
    filepath = os.path.join(GENERATED_FILES_DIR, filename)
    wb.save(filepath)

    return {
        "filename": filename,
        "filepath": filepath,
        "format": "xlsx",
        "title": title,
        "template": template,
        "file_size": os.path.getsize(filepath),
    }


# ═══════════════════════════════════════════════════════════════════════════════
# PDF DOCUMENT
# ═══════════════════════════════════════════════════════════════════════════════

@register_tool(
    name="generate_pdf",
    description="Generate a PDF document with text, tables, and embedded chart images. Returns {filename, filepath, format, title, template, file_size}.",
    parameters={
        "properties": {
            "title": {"type": "string", "description": "document title"},
            "template": {"type": "string", "description": "one of: research_report, modern_report"},
            "sections": {"type": "array", "description": "list of objects with keys: heading (string), content (string), table (optional: {headers: [string], rows: [[values]]}), chart_image (optional: filepath from generate_chart)"},
        }
    },
)
async def generate_pdf(title: str, template: str, sections: list[dict]) -> dict:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.units import inch
    from reportlab.lib.colors import HexColor, white, black
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import (
        SimpleDocTemplate,
        Paragraph,
        Spacer,
        Table,
        TableStyle,
        PageBreak,
    )
    from reportlab.pdfgen import canvas

    filename = f"{uuid.uuid4().hex[:8]}_{title.replace(' ', '_')[:30]}.pdf"
    filepath = os.path.join(GENERATED_FILES_DIR, filename)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72,
    )

    # ── Custom Styles ──
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=28,
        textColor=HexColor(f"#{PRIMARY_COLOR}"),
        spaceAfter=12,
        fontName="Helvetica-Bold",
    )

    subtitle_style = ParagraphStyle(
        "CustomSubtitle",
        parent=styles["Normal"],
        fontSize=14,
        textColor=HexColor(f"#{ACCENT_COLOR}"),
        spaceAfter=30,
        fontName="Helvetica-Oblique",
    )

    heading1_style = ParagraphStyle(
        "CustomH1",
        parent=styles["Heading1"],
        fontSize=18,
        textColor=HexColor(f"#{PRIMARY_COLOR}"),
        spaceAfter=12,
        spaceBefore=18,
        fontName="Helvetica-Bold",
    )

    heading2_style = ParagraphStyle(
        "CustomH2",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=HexColor(f"#{ACCENT_COLOR}"),
        spaceAfter=8,
        spaceBefore=12,
        fontName="Helvetica-Bold",
    )

    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=11,
        leading=16,
        textColor=black,
        fontName="Helvetica",
    )

    story = []

    # ── Cover Page ──
    story.append(Spacer(1, 2 * inch))
    story.append(Paragraph(title, title_style))
    story.append(Paragraph(_snake_to_title(template), subtitle_style))
    story.append(Spacer(1, 0.5 * inch))
    story.append(
        Paragraph(
            f"Generated by Life OS — {datetime.now().strftime('%B %d, %Y')}",
            ParagraphStyle(
                "Date",
                parent=styles["Normal"],
                fontSize=10,
                textColor=HexColor("#888888"),
                alignment=1,
                fontName="Helvetica-Oblique",
            ),
        )
    )
    story.append(PageBreak())

    # ── Sections ──
    for section in sections:
        heading = section.get("heading", "")
        content = section.get("content", "")

        story.append(Paragraph(heading, heading1_style))

        for para_text in content.split("\n"):
            para_text = para_text.strip()
            if not para_text:
                continue
            if para_text.startswith("### "):
                story.append(Paragraph(para_text[4:], heading2_style))
            elif para_text.startswith("- ") or para_text.startswith("• "):
                story.append(Paragraph(f"• {para_text[2:]}", body_style))
            else:
                story.append(Paragraph(para_text, body_style))

        # Optional table
        table_data = section.get("table")
        if table_data:
            headers = table_data.get("headers", [])
            rows = table_data.get("rows", [])
            if headers and rows:
                data = [headers] + [[str(c) for c in row] for row in rows]
                t = Table(data, hAlign="LEFT")
                t.setStyle(
                    TableStyle(
                        [
                            ("BACKGROUND", (0, 0), (-1, 0), HexColor(f"#{PRIMARY_COLOR}")),
                            ("TEXTCOLOR", (0, 0), (-1, 0), white),
                            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                            ("FONTSIZE", (0, 0), (-1, 0), 11),
                            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                            ("BACKGROUND", (0, 1), (-1, -1), HexColor("#f9f9f9")),
                            ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#dddddd")),
                            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                            ("FONTSIZE", (0, 1), (-1, -1), 10),
                            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, HexColor("#f5f5f5")]),
                            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                        ]
                    )
                )
                story.append(Spacer(1, 12))
                story.append(t)

        # Optional chart image
        chart_image = section.get("chart_image")
        if chart_image and os.path.exists(chart_image):
            from reportlab.platypus import Image as RLImage
            story.append(Spacer(1, 12))
            img = RLImage(chart_image, width=5.5 * inch, height=3.3 * inch)
            story.append(img)

        story.append(Spacer(1, 18))

    # ── Footer with page numbers ──
    def add_page_num(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 9)
        canvas.setFillColor(HexColor("#888888"))
        canvas.drawCentredString(
            letter[0] / 2, 0.5 * inch, f"Life OS — {title} — Page {doc.page}"
        )
        canvas.restoreState()

    doc.build(story, onFirstPage=add_page_num, onLaterPages=add_page_num)

    return {
        "filename": filename,
        "filepath": filepath,
        "format": "pdf",
        "title": title,
        "template": template,
        "file_size": os.path.getsize(filepath),
    }
