"""add_agent_interaction_metadata_and_generated_files

Revision ID: 13a99079a597
Revises: 9512167cc148
Create Date: 2026-05-10 17:39:10.903864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13a99079a597'
down_revision: Union[str, None] = '9512167cc148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('template_used', sa.String(), nullable=True),
    sa.Column('source_agent', sa.String(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_files_user_id'), 'generated_files', ['user_id'], unique=False)
    op.add_column('agent_interactions', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_interactions', 'extra_metadata')
    op.drop_index(op.f('ix_generated_files_user_id'), table_name='generated_files')
    op.drop_table('generated_files')
    # ### end Alembic commands ###
