"""add_api_key_disclaimer_dismissed

Revision ID: 4d68fab68f70
Revises: 42383fa2589b
Create Date: 2026-05-16 21:55:31.358149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d68fab68f70'
down_revision: Union[str, None] = '42383fa2589b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key_disclaimer_dismissed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_key_disclaimer_dismissed')
    # ### end Alembic commands ###
