"""initial schema

Revision ID: 7049521a391d
Revises: 
Create Date: 2026-05-08 20:35:39.547016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7049521a391d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('onboarding_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agent_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('full_response', sa.Text(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('overridden', sa.Boolean(), nullable=False),
    sa.Column('override_note', sa.Text(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_interactions_user_id'), 'agent_interactions', ['user_id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('checkin_type', sa.String(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=True),
    sa.Column('energy_score', sa.Integer(), nullable=True),
    sa.Column('stress_score', sa.Integer(), nullable=True),
    sa.Column('focus_score', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('exercised', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('wins', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('struggles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tasks_planned', sa.Integer(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('last_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_interacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interaction_frequency_days', sa.Integer(), nullable=True),
    sa.Column('times_nudged', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_user_id'), 'relationships', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('times_deferred', sa.Integer(), nullable=False),
    sa.Column('first_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('execution_output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('user_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('peak_days', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('low_days', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('peak_hour_start', sa.Integer(), nullable=True),
    sa.Column('peak_hour_end', sa.Integer(), nullable=True),
    sa.Column('time_estimation_bias', sa.Float(), nullable=True),
    sa.Column('avg_completion_rate_7d', sa.Float(), nullable=True),
    sa.Column('top_avoidance_categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('avg_deferral_count', sa.Float(), nullable=True),
    sa.Column('mood_sleep_correlation', sa.Float(), nullable=True),
    sa.Column('mood_exercise_correlation', sa.Float(), nullable=True),
    sa.Column('checkin_streak', sa.Integer(), nullable=False),
    sa.Column('longest_checkin_streak', sa.Integer(), nullable=False),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('life_focus_areas', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('typical_wake_time', sa.Time(), nullable=True),
    sa.Column('typical_sleep_time', sa.Time(), nullable=True),
    sa.Column('peak_energy_start', sa.Time(), nullable=True),
    sa.Column('peak_energy_end', sa.Time(), nullable=True),
    sa.Column('low_energy_windows', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_estimation_bias', sa.Float(), nullable=False),
    sa.Column('avg_tasks_completed', sa.Float(), nullable=True),
    sa.Column('avoidance_categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('communication_style', sa.String(), nullable=True),
    sa.Column('coaching_tone', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('user_patterns')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_relationships_user_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_checkins_user_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_agent_interactions_user_id'), table_name='agent_interactions')
    op.drop_table('agent_interactions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
