"""add_agent_tracking_chat_messages

Revision ID: 9512167cc148
Revises: 7abadb77ad8b
Create Date: 2026-05-10 02:45:11.143367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9512167cc148'
down_revision: Union[str, None] = '7abadb77ad8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.add_column('agent_interactions', sa.Column('status', sa.String(), server_default='completed', nullable=False))
    op.add_column('agent_interactions', sa.Column('task_id', sa.UUID(), nullable=True))
    op.add_column('agent_interactions', sa.Column('trigger_type', sa.String(), nullable=True))
    op.add_column('agent_interactions', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agent_interactions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agent_interactions', sa.Column('error_message', sa.Text(), nullable=True))
    op.create_index(op.f('ix_agent_interactions_agent_name'), 'agent_interactions', ['agent_name'], unique=False)
    op.create_foreign_key(None, 'agent_interactions', 'tasks', ['task_id'], ['id'])
    op.add_column('tasks', sa.Column('assigned_agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'assigned_agent')
    op.drop_constraint(None, 'agent_interactions', type_='foreignkey')
    op.drop_index(op.f('ix_agent_interactions_agent_name'), table_name='agent_interactions')
    op.drop_column('agent_interactions', 'error_message')
    op.drop_column('agent_interactions', 'completed_at')
    op.drop_column('agent_interactions', 'started_at')
    op.drop_column('agent_interactions', 'trigger_type')
    op.drop_column('agent_interactions', 'task_id')
    op.drop_column('agent_interactions', 'status')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
